---
version: 1
dependencies:
#  galaxy: requirements.yml
#  python: requirements.txt
  system: bindep.txt

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8'

#additional_build_steps:
#  prepend: |
#    RUN whoami
#    RUN cat /etc/os-release
#  append:
#    - RUN dnf install -y rhel-system-roles
#    - RUN ls -la /etc
