---
- name: rerun EE's and sincy with container image repo
  hosts: "{{ target_hosts }}"
  vars: 
    registry_url: quay.io/mbredeme
    base_image_registry_url: registry.redhat.io
    user_dir: /home/mbredeme 
    
  tasks:  
    - name: get EE list
      shell:
        cmd: ls -d */
        chdir: "{{ user_dir }}/execution_environments"
      register: r_ee_list

    - name: show r_ee_list
      debug:
        var: item [:-1]
      loop: "{{ r_ee_list.stdout_lines }}"
      when: item [:-1] != 'roles'

    - name: login to registry.redhat.io
      containers.podman.podman_login:
        username: "{{ lookup('env', 'PORTAL_USERNAME') }}"
        password: "{{ lookup('env', 'PORTAL_PASSWORD') }}"
        registry: "{{ base_image_registry_url }}"

#    - name: login to registry.redhat.io to pull ubi default minimal
#      shell:
#        cmd: podman login -u {{ lookup('env', 'PORTAL_USERNAME') }} -p {{ lookup('env', 'PORTAL_PASSWORD') }} registry.redhat.io
#        chdir: /home/mbredeme/execution_environments

    - name: build EE's
      shell:
        cmd: ansible-builder build -v3 -t {{ registry_url }}/{{ item [:-1] }}
        chdir: /home/mbredeme/execution_environments/{{ item [:-1] }}
      loop: "{{ r_ee_list.stdout_lines }}"
