---
version: 1
dependencies:
  galaxy: requirements.yml
  # python: requirements.txt
  # system: bindep.txt

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8'

ansible_config: 'ansible.cfg'

#additional_build_steps:
#  prepend: |
#    RUN whoami
#    RUN cat /etc/os-release
#  append:
#    - RUN dnf install -y rhel-system-roles
#    - RUN ls -la /etc
