---
# tasks file for install_guilder
- name: install builder
  yum:
    name: 
      - ansible-builder
      - git
      - tree
    state: present

- name: remove execution_environments directory
  file:
    path: /home/mbredeme/execution_environments
    state: absent

- name: ensure EE projects directory exists
  git: 
    repo: https://github.com/mkbredem/ansible-builder.git
    dest: /home/mbredeme/execution_environments

- name: Recursively change ownership of execution_environments directory
  ansible.builtin.file:
    path: /home/mbredeme/execution_environments
    state: directory
    recurse: yes
    owner: mbredeme
    group: mbredeme
    mode: '0644'

- name: ensure ansible.cfg file exists
  template:
    src: templates/ansible.cfg.j2
    dest: /home/mbredeme/execution_environments/ansible.cfg
    mode: '0644'
    owner: mbredeme
    group: mbredeme
